# Metadata for your course

title: <script>alert(document.domain)</script># a name for your Learning Lab course
tagline: test# a short description for your Learning Lab course, displayed on the course catalog
description: test# a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: test# the name of the repository when it is created for the learner
  repo: test# the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createLabel
  name: another label
  color: f87000
  description: This label is used to label things

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: take a shit # the title of the step, shown to the learner in the course progress page
  description: go to the bathroom and take a huuuuuge shit# the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  event: issue # a list of the actions that will occur when the step is triggered by an event
  actions:
  - type: createLabel
    name: another label
    color: f87000
    description: This label is used to label things
